baseURL = "https://agencjawroclawska.pl"
description = "Hugo port of the Themefisher’s Kross Template"
languageCode = "pl-PL"
theme = "sc_aw"
title = "Agencja Wrocławska"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = "0.5"
[[styles.plugins.css]]
URL = ""
[[styles.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[styles.plugins.css]]
URL = "plugins/slick/slick.css"
[[styles.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[dodaj_pliki]]
dodaj_plik = ""
rodzaj_pliku = ""
