baseURL = "https://agencjawroclawska.pl"
description = "Hugo port of the Themefisher’s Kross Template"
dodaj_pliki = []
languageCode = "pl-PL"
theme = "sc_aw"
title = "Agencja Wrocławska"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = "0.5"
[[ScAssets]]
ScAsset = "/uploads/main.css"
rodzaj_pliku = "Styl"
