baseURL = "https://agencjawroclawska.pl"
description = "Hugo port of the Themefisher’s Kross Template"
languageCode = "pl-PL"
theme = "sc_aw"
title = ""
[params]
description = "Welcome to my website"
favico = ""
logo = "/uploads/banner_w_tiles.jpg"
metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
paginatedsections = ["posts"]
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110