ScAssets = []
baseURL = "https://agencjawroclawska.pl"
description = "Hugo port of the Themefisher’s Kross Template"
dodaj_pliki = []
languageCode = "pl-PL"
scAssets = []
theme = "sc_aw"
title = "Agencja Wrocławska"
[[scriptsStyles.scassets]]
assetType = "Styl"
scasset = "/uploads/main.css"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = "0.5"
[[params]]
style = ""
[[params.styles]]
style = "/uploads/main.css"
