baseURL = "/"
canonifyURLs = true
description = "Hugo port of the Themefisher’s Kross Template"
enableRobotsTXT = true
landscapePhotoWidths = [2500, 1500, 1000]
languageCode = "pl-PL"
portraitPhotoWidths = [1500, 1000, 750]
theme = "sc_aw"
title = "Agencja Wrocławska"
[[menu.main]]
name = "Pozycjonowanie"
url = "#"
weight = 1
[params]
description = "Welcome to my website"
email_header = "kontakt@agencjawroclawska.pl"
favico = ""
header_adres_email = "kontakt@agencjawroclawska.pl"
header_numer_telefonu = "666 666 666"
header_numer_telefonu_link = "+48666666666"
landscapePhotoWidths = [3400, 2560, 1920, 1600, 1366, 1200, 992, 786, 560]
logo = "/uploads/logo-aw-black.svg"
logo_dark_mode = "/uploads/logo-aw-white.svg"
metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
paginatedsections = ["posts"]
portraitPhotoWidths = [1500, 1000, 750, 500]
[permalinks]
"/" = "/:slug/"
categories = "/kategoria/:slug/"
page = "/:slug/"
posts = "/:slug/"
tags = "/tag/:slug/"
[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "letters"
weight = 100
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
category = "categories"
letter = "letters"
tag = "tags"
