baseURL = "https://agencjawroclawska.pl"
description = "Hugo port of the Themefisher’s Kross Template"
languageCode = "pl-PL"
theme = "sc_aw"
title = "Agencja Wrocławska"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = "0.5"
