baseURL = "/"
canonifyURLs = true
description = "Hugo port of the Themefisher’s Kross Template"
enableRobotsTXT = true
languageCode = "pl-PL"
theme = "sc_aw"
title = "Agencja Wrocławska"
landscapePhotoWidths = [2500, 1500, 1000]
portraitPhotoWidths = [1500, 1000, 750]
[[menu.main]]
identifier = "about"
name = "about hugo"
pre = "<i class='fa fa-heart'></i>"
url = "/about/"
weight = -110
[params]
description = "Welcome to my website"
favico = ""
logo = "/uploads/banner_w_tiles.jpg"
metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
paginatedsections = ["posts"]
landscapePhotoWidths = [3400, 2560, 1920, 1600, 1366, 1200, 992, 786, 560]
portraitPhotoWidths = [1500, 1000, 750, 500]
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[permalinks]
"/" = "/:slug/"
posts = "/:slug/"
page = "/:slug/"
[taxonomies]
  category = "categories"
  tag = "tags"